DROP TABLE IF EXISTS student

CREATE TABLE student
(
	id INT NOT NULL,
	name VARCHAR(50),
	age INT
);

ALTER TABLE student
ALTER COLUMN name VARCHAR(50) NOT NULL;

ALTER TABLE student
ALTER COLUMN age INT NOT NULL;

INSERT INTO student
VALUES (1, NULL, NULL)